name: Build 64Bit

on: [push, pull_request]

jobs:

  MIN-GW:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
    - name : Build main.cpp
    - run: |
       & 'x86_64-w64-mingw32-g++' -o ./compile/result ./src/main.cpp
    - name : Upload Artifact 
    - uses : actions/upload-artifact@v2.3.1
      with:
          name: RentalMobil
          path: ./compile/
          retention-days: 2
