name: Build 64Bit

on: [push, pull_request]

jobs:

  MIN-GW:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
    - run: g++ -v
